In [2]:
import numpy as np
import scipy.constants as con

In [5]:
class Ring:
    def __init__(self, n):
        self.dbonds = 2 * n + 1
        self.homo = self.dbonds
        self.lumo = self.homo + 1
        self.ly = 0.28e-9
        self.lx = (0.24e-9) * n


def listEnergies(molecule):
    E0 = (con.hbar**2 * con.pi**2)/(2*con.m_e)
    earray = []
    nxarray = []
    nyarray = []
    for nx in range(1,molecule.lumo + 1):
        for ny in range(1,molecule.lumo+1):
            energy = (E0 * ((nx**2 / (molecule.lx)**2) + (ny**2 / (molecule.ly)**2)))/con.e
            earray.append([energy])
            nxarray.append([nx])
            nyarray.append([ny])
    a = np.hstack([nxarray,nyarray,earray])
    sort = a[a[:,2].argsort()]
    return sort

naphthelene = Ring(2)
anthracene = Ring(3)
tetracene = Ring(4)

nEnergies = listEnergies(naphthelene)
aEnergies = listEnergies(anthracene)
tEnergies = listEnergies(tetracene)

In [6]:
np.savetxt('naphtheleneEnergies.txt',nEnergies, delimiter=', ', header='Napthelene Calculated Energies, (nx, ny, energy)')
np.savetxt('anthraceneEnergies.txt',aEnergies, delimiter=', ', header='Anthracene Calculated Energies, (nx, ny, energy)')
np.savetxt('tetraceneEnergies.txt',tEnergies, delimiter=', ', header='Napthelene Calculated Energies, (nx, ny, energy)')

In [18]:
#create array
x = np.array([14, 12, 8, 10, 5, 7, 11, 9, 2,4,4,-1]).reshape(4,3)

print(x, np.shape(x))

#define new matrix with rows sorted in ascending order by values in second column
x_sorted_asc = x[x[:,2].argsort()]

#view sorted matrix
print(x_sorted_asc)

[[14 12  8]
 [10  5  7]
 [11  9  2]
 [ 4  4 -1]] (4, 3)
[[ 4  4 -1]
 [11  9  2]
 [10  5  7]
 [14 12  8]]


In [20]:
#create array
x = listEnergies(naphthelene)

print(x, np.shape(x))

#define new matrix with rows sorted in ascending order by values in second column
x_sorted_asc = x[x[:,2].argsort()]

#view sorted matrix
print(x_sorted_asc)

[[1.00000000e+00 1.00000000e+00 1.02993978e-18]
 [1.00000000e+00 2.00000000e+00 3.33529720e-18]
 [1.00000000e+00 3.00000000e+00 7.17755957e-18]
 [1.00000000e+00 4.00000000e+00 1.25567269e-17]
 [1.00000000e+00 5.00000000e+00 1.94727992e-17]
 [1.00000000e+00 6.00000000e+00 2.79257764e-17]
 [2.00000000e+00 1.00000000e+00 1.81440168e-18]
 [2.00000000e+00 2.00000000e+00 4.11975910e-18]
 [2.00000000e+00 3.00000000e+00 7.96202147e-18]
 [2.00000000e+00 4.00000000e+00 1.33411888e-17]
 [2.00000000e+00 5.00000000e+00 2.02572611e-17]
 [2.00000000e+00 6.00000000e+00 2.87102383e-17]
 [3.00000000e+00 1.00000000e+00 3.12183818e-18]
 [3.00000000e+00 2.00000000e+00 5.42719560e-18]
 [3.00000000e+00 3.00000000e+00 9.26945798e-18]
 [3.00000000e+00 4.00000000e+00 1.46486253e-17]
 [3.00000000e+00 5.00000000e+00 2.15646976e-17]
 [3.00000000e+00 6.00000000e+00 3.00176748e-17]
 [4.00000000e+00 1.00000000e+00 4.95224928e-18]
 [4.00000000e+00 2.00000000e+00 7.25760671e-18]
 [4.00000000e+00 3.00000000e+00 1.109986